---
- name: install server packages
  apt:
    name: "{{ packages }}"
    cache_valid_time: 3600
  vars:
    packages:
    - postfix
    - libsasl2-modules
  notify: restart postfix

- name: postfix relayhost credentials
  copy:
    dest:  /etc/postfix/sasl/passwd
    content: "[{{ postfix_relayhost_fqdn }}]:{{ postfix_relayhost_port }} {{ postfix_relayhost_username }}:{{ postfix_relayhost_password }}\n"
    mode: '0400'
  notify: postmap sasl_passwd
  when: postfix_relayhost_fqdn is defined

- name: postfix reply_to_header map
  copy:
    dest: /etc/postfix/reply_to_header
    content: "/^Content-Transfer-Encoding:/i PREPEND Reply-to: {{ default_email }}\n"
  notify: restart postfix

- name: postfix main config file
  template:
    dest: /etc/postfix/main.cf
    src: main.cf
  notify: restart postfix

- name: keep postfix running
  service:
    name: postfix
    state: started
    enabled: true
